name: End to End Test

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GO_MODULES_TOKEN }}
      - name: Configure Git for private modules
        run: |
          git config --global url."https://x-access-token:${{ secrets.GO_MODULES_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GO_MODULES_TOKEN }}@github.com" > ~/.git-credentials
        shell: bash
      - name: Config Git
        run: |
          git config --global user.name "test.runner"
          git config --global user.email "test@runner.com"
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Configure Go for private modules
        run: |
          go env -w GOPRIVATE=github.com/datadatdat/*
          go env -w GONOPROXY=github.com/datadatdat/*
          go env -w GONOSUMDB=github.com/datadatdat/*
          go env -w GOPROXY=direct
        shell: bash
        env:
          GOPRIVATE: github.com/datadatdat/*
          GONOPROXY: github.com/datadatdat/*
          GONOSUMDB: github.com/datadatdat/*
      - name: Output Kernel Info
        run: |
         docker pull busybox
         docker run busybox uname -a
      - name: Build Titan
        run: make build
        shell: bash
        env:
          GOPRIVATE: github.com/datadatdat/*
          GONOPROXY: github.com/datadatdat/*
          GONOSUMDB: github.com/datadatdat/*
          GIT_TERMINAL_PROMPT: 0
      - name: Setup Test Requirements
        run: |
          ssh-keygen -b 2048 -t rsa -f ./sshKey -q -N ""
      - name: Run Test Suit
        run: |
          export PATH=$GITHUB_WORKSPACE/build:$PATH
          make e2e
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
